### ISSUE TITLE
Error: ImportError: cannot import name 'DeviceException' from 'miio.device'

### ISSUE THREAD

**Issue by Oksion** [Cheaterdev/clear_grass-ha#5]
In the latest HA updates, developers broke the functionality of this custom component

ImportError: cannot import name 'DeviceException' from 'miio.device' (/usr/local/lib/python3.7/site-packages/miio/device.py)

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 777, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 279, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/clear_grass/sensor.py", line 7, in <module>
    from miio.device import Device, DeviceException
ImportError: cannot import name 'DeviceException' from 'miio.device' (/usr/local/lib/python3.7/site-packages/miio/device.py)`

**Comment by Cheaterdev** [comment]
Hi! I've updated broken files. It should work now.

**Comment by Oksion** [comment]
Thanks a lot, it worked
